package dinson.customview.db.model;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ZHIHU_TUCAO".
 */
@Entity
public class ZhihuTucao implements Parcelable {

    @Id
    private Long id;
    private int date;

    @NotNull
    private String display_date;

    @NotNull
    private String images;

    @NotNull
    private String title;
    private String content;

    @Generated(hash = 1845517944)
    public ZhihuTucao() {
    }

    public ZhihuTucao(Long id) {
        this.id = id;
    }

    @Generated(hash = 1030154321)
    public ZhihuTucao(Long id, int date, @NotNull String display_date, @NotNull String images,
            @NotNull String title, String content) {
        this.id = id;
        this.date = date;
        this.display_date = display_date;
        this.images = images;
        this.title = title;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getDate() {
        return date;
    }

    public void setDate(int date) {
        this.date = date;
    }

    @NotNull
    public String getDisplay_date() {
        return display_date;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDisplay_date(@NotNull String display_date) {
        this.display_date = display_date;
    }

    @NotNull
    public String getImages() {
        return images;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setImages(@NotNull String images) {
        this.images = images;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }


    //    private Long id;
//    private int date;
//    private String display_date;
//    private String images;
//    private String title;
//    private String content;
    // 1.必须实现Parcelable.Creator接口,否则在获取Person数据的时候，会报错，如下：
    // android.os.BadParcelableException:
    // Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class com.um.demo.Person
    // 2.这个接口实现了从Percel容器读取Person数据，并返回Person对象给逻辑层使用
    // 3.实现Parcelable.Creator接口对象名必须为CREATOR，不如同样会报错上面所提到的错；
    // 4.在读取Parcel容器里的数据事，必须按成员变量声明的顺序读取数据，不然会出现获取数据出错
    // 5.反序列化对象
    protected ZhihuTucao(Parcel in) {
        date = in.readInt();
        display_date = in.readString();
        images = in.readString();
        title = in.readString();
        content = in.readString();
    }


    @Override
    public void writeToParcel(Parcel dest, int flags) {
        if (id == null) {
            dest.writeByte((byte) 0);
        } else {
            dest.writeByte((byte) 1);
            dest.writeLong(id);
        }
        dest.writeInt(date);
        dest.writeString(display_date);
        dest.writeString(images);
        dest.writeString(title);
        dest.writeString(content);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<ZhihuTucao> CREATOR = new Creator<ZhihuTucao>() {
        @Override
        public ZhihuTucao createFromParcel(Parcel in) {
            return new ZhihuTucao(in);
        }

        @Override
        public ZhihuTucao[] newArray(int size) {
            return new ZhihuTucao[size];
        }
    };
}
